# Sniperkit-Bot
# - Status: analyzed

version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\corestoreio\pkg

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

build: off
deploy: off

services:
  - mysql               # start MySQL 5.6 service

environment:
  GOPATH: c:\gopath

install:
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - set PATH=c:\MinGW\bin;C:\cygwin\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -t -d -v ./...

build_script:
  - c:\MinGW\bin\make.exe testnodb
